### ISSUE TITLE
Removing `$` from method names

### ISSUE THREAD

**Issue by baldram** [rcardin/raise4s#2]
Thanks for the work on this library and the idea to create a Scala version of the successful Kotlin library.
I'd like to note a suggestion for improvement, referring to a Twitter thread (https://x.com/riccardo_cardin/status/1780289666526179395).

**Problem**: using the `$` symbol in a name is unnatural and hard to get used to, but it's also dangerous.

- Danger? Read more details here: https://github.com/scala/scala3/issues/19274#issuecomment-1857804342
- What about reserved words then?

  - 👎  Changing the name might not be a good idea. For example, for `try`, alternatives like `trial`, `attempt`, `prova`, etc., not the best option.
  - 👎 Using underscore. `_try`, also not the best option
  - 👍 Options are limited. A sensible one seems to be creating a name that resembles the original, for example, for `try`, one of `inTry`, `withinTry`, `asTry`, `safeTry`, `evalTry`, `tryBlock`, `tryThis`, `inTry`, etc., whatever you prefer. 
  - Then we must consistently name everything similarly, including those that are legally permissible. Let's take exemplary suggestion (but ultimately, we need to choose one that best harmonises with all the names). We'll end up with something like this: for builders `asTry`, `asEither`, `asOption` and for raises: `inCatch`, and so on.

What do you think?

**Comment by rcardin** [comment]
At first thought, I would:

- Rename the `$try` method in `asTry` since it creates a `Try[A]` instance.
- Rename the `$catch` method in `attempt`.

By the way, I hope we'll not need builders anymore in the future: #3

**Comment by baldram** [comment]
So we would change just those, without a consistent convention? That means without adding `asEither`, `asOption` as well?

**Comment by rcardin** [comment]
Let us resolve one problem at a time. The more contingent problem is that we don't want `$` notation in methods' names. The issue title also states it :P

Then, let's use the new notation. If we start to feel uncomfortable with the `either` and `option` builder's names, we can change them in some dedicated issues.
